name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4']
        dependencies: [lowest, highest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, pdo_mysql, sqlite, redis
          tools: composer:v2, phpunit, phpstan, phpcs, psalm
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M
            memory_limit=1G
            max_execution_time=120

      - name: Validate PHP
        run: php -v

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.dependencies }}" == "lowest" ]]; then
            composer update --prefer-lowest --prefer-stable --no-progress --no-interaction
          else
            composer update --no-progress --no-interaction
          fi

      # 🐞 Static analysis for potential bugs
      - name: Run PHPStan
        run: phpstan analyse app --level=max

      - name: Run Psalm
        run: psalm --no-progress --output-format=compact

      # 🎨 Coding standards check
      - name: Run PHPCS (PSR-12)
        run: phpcs --standard=PSR12 src/

      # 🧪 PHPUnit with Coverage
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      # 📊 Upload coverage report to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
